"""
European structural steel catalog.

Section data lives in JSON datasets under ``data/catalog/`` (one file per family),
generated by ``scripts/build_catalog.py`` from EN section tables. This module loads
them at import time and exposes lookup helpers.

All dimensions in millimetres; mass in kg/m. Every profile is normalised to expose
``h, b, tw, tf`` so existing geometry/seating code keeps working regardless of the
underlying shape:

  open I/H/U/Tee : tabulated h, b, tw, tf, r
  RHS / SHS      : h, b, t  -> tw = tf = t (+ ro)
  CHS            : d, t      -> h = b = d, tw = tf = t
  L (angle)      : a, b, t   -> h = a, b = b, tw = tf = t
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TypedDict

_DATA_DIR = Path(__file__).resolve().parent / "data" / "catalog"


class CatalogProfile(TypedDict, total=False):
    family: str
    shape: str
    h: float
    b: float
    tw: float
    tf: float
    r: float
    t: float
    d: float
    ro: float
    lip: float
    mass_per_m: float


def _normalize(raw: dict) -> CatalogProfile:
    """Coerce a raw dataset record into a profile with guaranteed h/b/tw/tf."""
    shape = str(raw.get("shape", "I-beam"))
    h = float(raw.get("h", raw.get("d", 0.0)))
    b = float(raw.get("b", raw.get("d", h)))

    if "tw" in raw and "tf" in raw:
        tw = float(raw["tw"])
        tf = float(raw["tf"])
    else:
        # Hollow / angle sections carry a single wall thickness ``t``.
        t = float(raw.get("t", 0.0))
        tw = t
        tf = t

    profile: CatalogProfile = {
        "family": str(raw.get("family", "")),
        "shape": shape,
        "h": h,
        "b": b,
        "tw": tw,
        "tf": tf,
        "mass_per_m": float(raw.get("mass_per_m", 0.0)),
    }
    for opt in ("r", "t", "d", "ro", "lip"):
        if opt in raw:
            profile[opt] = float(raw[opt])
    return profile


def _load_catalog() -> dict[str, CatalogProfile]:
    profiles: dict[str, CatalogProfile] = {}
    if not _DATA_DIR.is_dir():
        raise FileNotFoundError(
            f"Catalog data directory missing: {_DATA_DIR}. "
            "Run: python scripts/build_catalog.py"
        )
    for path in sorted(_DATA_DIR.glob("*.json")):
        records = json.loads(path.read_text(encoding="utf-8"))
        for raw in records:
            designation = str(raw["designation"])
            key = designation.upper().replace(" ", "")
            profiles[key] = _normalize(raw)
    if not profiles:
        raise RuntimeError(f"No catalog sections loaded from {_DATA_DIR}")
    return profiles


EUROPEAN_PROFILES: dict[str, CatalogProfile] = _load_catalog()
CATALOG_PROFILE_NAMES: tuple[str, ...] = tuple(EUROPEAN_PROFILES.keys())

# Accept common aliases: Z200x2.0 → Z200x2, C150x2.00 → C150x2, etc.
_CF_ALIAS = re.compile(
    r"^([A-Z]+)(\d+(?:\.\d+)?)X(\d+(?:\.\d+)?)$",
    re.IGNORECASE,
)


def _canonical_profile_key(name: str) -> str:
    """Normalise a designation to the catalog lookup key."""
    key = name.strip().upper().replace(" ", "")
    if key in EUROPEAN_PROFILES:
        return key
    m = _CF_ALIAS.match(key)
    if m:
        prefix, depth, thick = m.groups()
        alt = f"{prefix.upper()}{float(depth):g}X{float(thick):g}"
        if alt in EUROPEAN_PROFILES:
            return alt
    return key


def get_profile(name: str) -> CatalogProfile:
    """Return catalog dimensions for a standard profile name (case-insensitive)."""
    key = _canonical_profile_key(name)
    profile = EUROPEAN_PROFILES.get(key)
    if profile is None:
        raise ValueError(
            f"Unknown profile '{name}'. {len(CATALOG_PROFILE_NAMES)} sections available "
            "(see /api/catalog)."
        )
    return profile


def has_profile(name: str) -> bool:
    return _canonical_profile_key(name) in EUROPEAN_PROFILES


def names_by_shape(shape: str) -> frozenset[str]:
    """Catalog designations whose render shape matches (e.g. 'I-beam')."""
    return frozenset(
        name for name, data in EUROPEAN_PROFILES.items() if data.get("shape") == shape
    )


def list_families() -> list[dict[str, object]]:
    """Per-family summary: section count + size range, for prompts/UI."""
    families: dict[str, dict[str, object]] = {}
    for name, data in EUROPEAN_PROFILES.items():
        fam = str(data.get("family", "")) or "?"
        entry = families.setdefault(
            fam,
            {"family": fam, "shape": data.get("shape"), "count": 0, "min_h": None, "max_h": None},
        )
        entry["count"] = int(entry["count"]) + 1  # type: ignore[arg-type]
        h = float(data.get("h", 0.0))
        lo = entry["min_h"]
        hi = entry["max_h"]
        entry["min_h"] = h if lo is None else min(float(lo), h)
        entry["max_h"] = h if hi is None else max(float(hi), h)
    return sorted(families.values(), key=lambda e: str(e["family"]))


def list_profiles(family: str | None = None) -> list[dict[str, str | float]]:
    """Serialize catalog for prompts or API discovery (optionally one family)."""
    fam_key = family.strip().upper() if family else None
    out: list[dict[str, str | float]] = []
    for name, data in EUROPEAN_PROFILES.items():
        if fam_key and str(data.get("family", "")).upper() != fam_key:
            continue
        out.append(
            {
                "profile_name": name,
                "family": str(data.get("family", "")),
                "shape": str(data.get("shape", "")),
                "h_mm": data["h"],
                "b_mm": data["b"],
                "tw_mm": data["tw"],
                "tf_mm": data["tf"],
                "mass_per_m_kg": data.get("mass_per_m", 0.0),
            }
        )
    return out
